'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isPages=location.hostname.endsWith('.github.io');
if(isPages)document.querySelector('.navfoot').innerHTML='<span class="dot"></span> Published recording<br><small>Read-only scientific evidence</small>';
const sections=['Universe','Experiments','Structures','Energy & Materials','Lineage','Timeline','Research / Evidence','Progress','System Status'];
const slug=s=>s.toLowerCase().replace(/[^a-z]+/g,'-').replace(/-$/,'');
let recording, states, index=32, selected='o26', section='universe', timer=null, zoom=1, pan={x:0,y:0};
const current=()=>states[index], world=()=>current().state.world, terminal=()=>states.at(-1).state.world;
const tokenCount=w=>w.bank.length+Object.values(w.objects).reduce((n,o)=>n+o.tokens.length,0);
const eventLabel=f=>`event ${f.event.tick} · ${f.event.result.outcome}`;
const links=ids=>ids.map(id=>`<button data-object="${esc(id)}">${esc(id)}</button>`).join('');
function stop(){clearInterval(timer);timer=null;$('play').textContent='Play';}
function setTick(i){index=Math.max(0,Math.min(states.length-1,i));render();}
function render(){
  const w=world(),l=Ora.ledger(w);$('tick').textContent=index;$('scrub').value=index;$('scrubvalue').textContent=index;
  $('metrics').innerHTML=[['Present structures',Object.keys(w.objects).length,`${Object.keys(w.history).length} recorded births`,'Assembly does not establish life'],['Usable work',l.usable,'model work units',`${l.heat} heat · ${l.bonds} stored in bonds`],['Material inventory',l.atoms,'unique model atoms',`${l.ready} ready · ${l.nutrients} nutrients · ${l.waste} waste`],['Accounting',`${l.total} / 320`,'model work equivalents','Material and energy ledgers conserved']].map(([label,value,unit,note])=>`<div class="metric"><div class="label">${label}</div><div class="value"><strong>${value}</strong><small>${unit}</small></div><div class="note">${note}</div></div>`).join('');
  $('lastEvent').textContent=current().event ? `State ${index} follows ${eventLabel(current())}. Event ticks begin at 0.` : 'Genesis state · before event 0';
  $('back').disabled=index===0;$('next').disabled=index===states.length-1;
  renderAtlas();renderInspector();renderDetails();
}
function renderAtlas(){
  const w=world(),ids=Object.keys(terminal().history).sort((a,b)=>{const aa=terminal().history[a],bb=terminal().history[b];return aa.born_tick-bb.born_tick||a.localeCompare(b,undefined,{numeric:true});}), pos={};
  ids.forEach((id,i)=>{const o=terminal().history[id];if(o.born_tick<0){const n=Number(id.slice(1));pos[id]={x:70+(n%8)*86,y:45+Math.floor(n/8)*67};}else{const n=ids.filter(k=>terminal().history[k].born_tick>=0).indexOf(id);pos[id]={x:115+(n%5)*132,y:330+Math.floor(n/5)*65};}});
  const visible=ids.filter(id=>w.history[id]), ancestors=Ora.ancestors(w,selected),energy=$('overlay').value==='energy';
  const edges=visible.flatMap(id=>w.history[id].parents.map(p=>pos[p]?`<path class="edge ${ancestors.includes(id)&&ancestors.includes(p)?'highlight':''}" d="M ${pos[p].x} ${pos[p].y} Q ${pos[p].x} ${pos[id].y-35} ${pos[id].x} ${pos[id].y}"/>`:''));
  $('view').innerHTML=`<svg class="atlas" viewBox="0 0 780 470" role="img" aria-label="Recorded structures and consumed-parent links, schematic only"><g id="network" transform="translate(${pan.x} ${pan.y}) scale(${zoom})">${edges.join('')}${visible.map(id=>{const o=w.history[id],live=w.objects[id],p=pos[id],r=11+o.atoms.length*3;return `<g class="node ${live?'present':''} ${id===selected?'selected':''}" data-object="${esc(id)}" role="button" tabindex="0" aria-label="Inspect structure ${esc(id)}${live?' present':' retired'}"><circle cx="${p.x}" cy="${p.y}" r="${r}"/><text x="${p.x}" y="${p.y+3}" text-anchor="middle">${energy?(live?live.tokens.length:0):esc(o.bits)}</text><text x="${p.x}" y="${p.y+r+13}" text-anchor="middle">${esc(id)}</text></g>`;}).join('')}</g></svg>`;
  const svg=$('view').querySelector('svg');let drag;
  svg.addEventListener('pointerdown',e=>{if(e.target.closest('[data-object]'))return;drag={x:e.clientX,y:e.clientY,initialX:pan.x,initialY:pan.y};svg.setPointerCapture(e.pointerId);});
  svg.addEventListener('pointermove',e=>{if(!drag)return;const rect=svg.getBoundingClientRect();pan={x:(e.clientX-drag.x)*780/rect.width+drag.initialX,y:(e.clientY-drag.y)*470/rect.height+drag.initialY};$('network').setAttribute('transform',`translate(${pan.x} ${pan.y}) scale(${zoom})`);});
  svg.addEventListener('pointerup',()=>{drag=null;});svg.addEventListener('pointercancel',()=>{drag=null;});
}
function renderInspector(){
  const w=world(), o=w.history[selected], future=terminal().history[selected];
  if(!o){$('inspect').innerHTML=`<div class="empty">${esc(selected)} has not been created at state tick ${index}.<br><button data-tick="${future?future.born_tick+1:0}">Jump to recorded birth</button></div>`;return;}
  const live=w.objects[selected], lineage=Ora.ancestors(w,selected), interactions=Ora.history(recording,selected), ended=states.find(f=>f.state.world.history[selected]&&!f.state.world.objects[selected]);
  const functional=recording.frames.some(f=>f.state.simulation_tick<=index && f.event?.result.outcome==='converted'&&f.event.result.targets.includes(selected));
  $('inspect').innerHTML=`<div class="objectid">${esc(selected)}</div><span class="badge">${live?'PRESENT':'RETIRED'} · ${esc(o.origin.toUpperCase())}</span><div class="bits">${[...o.bits].map(b=>`<span>${b}</span>`).join('')}</div><dl><dt>Birth event tick</dt><dd>${o.born_tick<0?'Genesis (−1)':o.born_tick}</dd><dt>Recorded sequence</dt><dd>${esc(o.bits)}</dd><dt>Material units</dt><dd>${o.atoms.length}</dd><dt>Work owned now</dt><dd>${live?live.tokens.length:'No current ownership'}</dd><dt>Producer</dt><dd>${esc(o.producer||'None recorded')}</dd><dt>Template parent</dt><dd>${esc(o.template_parent||'None recorded')}</dd><dt>Own-funded birth</dt><dd>${o.own_funded?'Yes':'No'}</dd><dt>Sequence match</dt><dd>${o.sequence_match?'Yes':'No'}</dd><dt>Retirement state</dt><dd>${ended?ended.state.simulation_tick:'Not recorded'}</dd></dl><div class="inspectnote">${o.atoms.length>1?'Assembled polymer':'Genesis monomer'}. ${functional?'A nutrient-capture event is recorded.':'No verified functional designation shown.'} Self-maintenance, reproduction, and inherited function are not established by this reference.</div><h3>Consumed parents & ancestry</h3><div class="chips">${links(lineage.filter(x=>x!==selected))||'<p>No recorded parent objects.</p>'}</div><h3>Material roots</h3>${o.atoms.map(a=>`<details><summary>${esc(a)} · bit ${esc(w.atoms[a].bit)}</summary><pre>${esc(JSON.stringify(w.atoms[a],null,2))}</pre><p>Recorded holders: ${Object.entries(terminal().history).filter(([,h])=>h.atoms.includes(a)).map(([id])=>`<button data-object="${id}">${id}</button>`).join(' → ')}</p></details>`).join('')}<h3>Current work provenance</h3>${live?.tokens.length?live.tokens.map(t=>`<p>${esc(t.unit)} · ${esc(t.origin)}<br>Capture actor <button data-object="${esc(t.actor)}">${esc(t.actor)}</button> · event tick ${t.tick}${t.nutrient?' · '+esc(t.nutrient):''}</p>`).join(''):'<p>No usable tokens currently owned.</p>'}<h3>Entire recorded interaction history</h3><p>Includes future events beyond the selected tick; jump to inspect each state.</p>${interactions.map(f=>`<div class="historyitem"><button data-tick="${f.state.simulation_tick}">${eventLabel(f)}</button><p>${esc(f.event.result.targets.join(' + '))}${f.event.result.product?' → '+esc(f.event.result.product):''} · ${f.event.result.charged} charged · ${f.event.result.heat} heat</p><details><summary>Exact recorded interaction</summary><pre>${esc(JSON.stringify(f.event.result,null,2))}</pre></details></div>`).join('')||'<p>No interactions recorded for this object.</p>'}<details><summary>Immutable birth record</summary><pre>${esc(JSON.stringify(o,null,2))}</pre></details>`;
  // Birth-root actors are recorded provenance, not necessarily capture actors.
  $('inspect').innerHTML=$('inspect').innerHTML.replaceAll('Capture actor','Recorded actor').replaceAll('Retirement state','Retirement state (full history)');
  $('inspect').querySelectorAll('details').forEach(detail=>{
    const p=detail.querySelector('p');
    if(p?.textContent.startsWith('Recorded holders:')){
      const atom=detail.querySelector('summary').textContent.split(' ')[0];
      const holders=Object.entries(terminal().history).filter(([,h])=>h.atoms.includes(atom)).sort((a,b)=>a[1].born_tick-b[1].born_tick).map(([id])=>id);
      p.innerHTML='Recorded holders (birth order, full history): '+links(holders);
    }
  });
}
const sourceLink=(file,label)=>`<a href="https://github.com/JeremyHennessy/Ora2.0/blob/${recording.manifest.identity.source_revision}/docs/${file}" target="_blank" rel="noreferrer">${label}</a>`;
function chart(){const series=states.map(f=>Ora.ledger(f.state.world));const line=(key,color)=>`<polyline fill="none" stroke="${color}" stroke-width="2" points="${series.map((l,i)=>`${35+i*21},${165-l[key]*.45}`).join(' ')}"/>`;return `<svg class="chart" viewBox="0 0 760 195" role="img" aria-label="Work accounting by recorded tick"><path stroke="#29404f" d="M35 10 V165 H725" fill="none"/>${line('usable','#69dfcd')}${line('heat','#e9b078')}${line('bonds','#a99be3')}<text x="35" y="188">0</text><text x="690" y="188">32 ticks</text><text x="8" y="168">0</text><text x="4" y="28">320</text></svg><p>Teal: usable work · amber: heat · violet: bond work. Stored nutrient potential is included in the conservation ledger, not usable work.</p>`;}
function renderDetails(){
  const w=world(),l=Ora.ledger(w);let html='';
  if(section==='universe'||section==='experiments'||section==='research-evidence')html=`<span class="eyebrow">RESEARCH / EVIDENCE</span><h2>The frontier is self-sustaining structure</h2><p>This display follows HEARTBEAT-04, a bounded engineering continuity reference under the TEMPLATE-02 law, using existing development seed 1. It is not an independent scientific sample. The scientific pilot tested whether neutral private-work formation could yield a functioning, own-funded copied descendant.</p><p><b>Registered result: admission screen failed.</b> In 16 scientific initializations, active private accounts produced zero copies and zero functioning descendants. Shared-bank controls produced 26 copies, none subsequently functional. Controls included fixed implementation, priced ghost, untemplated production, and shared financing. The criterion was not satisfied.</p><p>${sourceLink('TEMPLATE-02-RECEIPT.md','Scientific results')} · ${sourceLink('TEMPLATE-02-PROTOCOL.md','Hypothesis, controls & criteria')} · ${sourceLink('HEARTBEAT-04-RECEIPT.md','Engineering continuity evidence')} · ${sourceLink('AI-RESEARCH-INTAKE.md','Source-backed research intake')}</p><p>Open questions: opportunity for private work accumulation, independent backup, storage-fault recovery, and isolation. No learning, life, or emergent intelligence claim is inferred from this viewer.</p>`;
  if(section==='energy-materials')html=`<h2>Energy & material accounting</h2>${chart()}<table><thead><tr><th>Recorded category</th><th>At state ${index}</th><th>Meaning</th></tr></thead><tbody>${[['Usable work',l.usable,'Private tokens + global bank'],['Heat / waste work',l.heat,'Dissipated model work units'],['Stored bond work',l.bonds,'One unit per bond'],['Nutrient potential',8*l.nutrients,'8 work equivalents per remaining nutrient'],['Total',l.total,'Conserved: 320 work equivalents'],['Ready material',l.ready,'Available atom IDs'],['Bound material',l.bound,'Atoms in present structures'],['Waste material',l.waste,'Retired atoms awaiting reclamation'],['Nutrient material',l.nutrients,'Atoms in nutrient stock']].map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table><p>Cumulative captured work: ${recording.frames.filter(f=>f.event&&f.state.simulation_tick<=index).reduce((n,f)=>n+f.event.result.endowed.filter(t=>t.origin==='nutrient').length,0)} tokens. Charged work: ${recording.frames.filter(f=>f.event&&f.state.simulation_tick<=index).reduce((n,f)=>n+f.event.result.charged,0)}. Exact spent/carried/discarded/returned token provenance appears in each interaction. These are abstract model units, not joules or chemical elements.</p>`;
  if(section==='structures'||section==='lineage')html=`<h2>${section==='lineage'?'Recorded ancestry':'All historical structures at this tick'}</h2><p>Select any object, including retired parents, to trace materials and interactions.</p><table><thead><tr><th>Structure</th><th>Sequence</th><th>Birth event</th><th>State</th><th>Consumed parents</th></tr></thead><tbody>${Object.entries(w.history).map(([id,o])=>`<tr><td><button data-object="${id}">${id}</button></td><td>${o.bits}</td><td>${o.born_tick}</td><td>${w.objects[id]?'Present':'Retired'}</td><td><div class="chips">${links(o.parents)||'Genesis'}</div></td></tr>`).join('')}</tbody></table>`;
  if(section==='timeline')html=`<h2>Complete recorded events</h2><p>Event k transforms state k into state k+1. Unavailable proposals are retained as evidence.</p>${states.filter(f=>f.event).map(f=>`<div class="historyitem"><button data-tick="${f.state.simulation_tick}">${eventLabel(f)}</button><p>${esc(f.event.result.targets.join(' + '))} ${f.event.result.product?' → '+esc(f.event.result.product):''}</p></div>`).join('')}`;
  if(section==='progress'){const stages=[['Build the universe','Implemented finite substrate','Atom identities, private tokens, neutral events and immutable object birth history are recorded.'],['Make the universe reliable','Bounded recovery verified','HEARTBEAT-01 through 04 establish finite counter/world process-exit continuity. Power-loss recovery, off-drive backup and hardened isolation remain open.'],['Discover self-sustaining structures','Current scientific frontier','TEMPLATE-02 admission screen failed. Assembled structures and copying controls do not establish self-maintenance.'],['Establish a persistent ecosystem','Not established','A finite stopped reference is not a persistent ecosystem.'],['Observe reproduction and evolution','Not established','Sequence copying without inherited function does not satisfy this gate.'],['Develop independent learning','Not established','No recorded learning evidence in this experiment.'],['Explore emergent intelligence','Not established','No supported intelligence claim.']];html=`<h2>Seven-stage research roadmap</h2><p>This is the requested presentation framework. The repository’s Experiment Plan uses separate research gates; these are not invented completion percentages.</p><div class="roadmap">${stages.map(([name,status,detail],i)=>`<details ${i===2?'open':''}><summary>${i+1}. ${name}<small>${status}</small></summary><p>${detail}</p></details>`).join('')}</div><p>${sourceLink('EXPERIMENT-PLAN.md','Repository research gates')} · ${sourceLink('TEMPLATE-02-RECEIPT.md','Stage 3 evidence')}</p>`;}
  if(section==='system-status'){const id=recording.manifest.identity;html=`<h2>Evidence identity & read-only boundary</h2><dl><dt>Experiment</dt><dd>${recording.experiment_id}</dd><dt>World</dt><dd>${esc(id.world_id)}</dd><dt>Reported terminal state</dt><dd>Stopped at tick 32</dd><dt>Process health</dt><dd>Unverified</dd><dt>Semantic validation</dt><dd>Frozen independent Python auditor at export</dd><dt>Browser validation</dt><dd>SHA-256, identity, sequence, events, conservation</dd><dt>Scientific outcome</dt><dd>Admission screen failed (separate pilot)</dd></dl><pre>Source revision: ${id.source_revision}\nRun: ${id.run_id}\nJournal SHA-256: ${recording.source_journal_sha256}\nTerminal state SHA-256: ${recording.audit.verified_state_sha256}</pre><p>The local loopback server exposes only this static observer and its exported recording. UI controls change the playback cursor and schematic view only. There are no mutation endpoints, simulation workers, experiment-launch controls, keys, or automatic updates.</p><p>The integrity manifest detects changed bytes relative to this local export. It is not a cryptographic signature or a defense against an actor replacing both bundle and manifest.</p>`;}
  if(['universe','experiments','research-evidence'].includes(section))html+=`<h3>Latest integrated research · ENERGY-01</h3><p>Source-pinned main receipt 2648b11: 4,192 authored cases / 22,624 events establish paid-capture feasibility under the installed law. The failed-encounter advantage disappears under cost matching; local storage capacity is below the unchanged copy debit. Zero natural worlds were run. This mechanism has no copying or reconstruction action, so it does not demonstrate reproduction or emergence.</p><p><a href="https://github.com/JeremyHennessy/Ora2.0/blob/2648b11829d991c2130ea31bdf1737182c1e077c/docs/ENERGY-01-RECEIPT.md" target="_blank" rel="noreferrer">ENERGY-01 result and limitations</a>. Next documented question: paid activated precursors and incremental reaction-energy coupling. This viewer continues to show the older, immutable HEARTBEAT-04 reference, not ENERGY-01 activity.</p>`;
  if(isPages)html=html.replace('The local loopback server exposes only this static observer and its exported recording.','GitHub Pages serves a fixed observer release and its published recording.');
  if(section==='experiments')html=`<h2>Available recorded experiment</h2><p>One independently audited reference is published. Select its universe to inspect the existing record; this does not execute an experiment.</p><dl><dt>Experiment</dt><dd>${esc(recording.experiment_id)}</dd><dt>World</dt><dd>${esc(recording.manifest.identity.world_id)}</dd><dt>Recorded states</dt><dd>${states.length}</dd><dt>Recorded events</dt><dd>${states.filter(f=>f.event).length}</dd><dt>Scope</dt><dd>HEARTBEAT-04 bounded engineering continuity reference, development seed 1</dd></dl><p><a href="#universe">Open recorded universe →</a></p><p>${sourceLink('HEARTBEAT-04-RECEIPT.md','Engineering continuity evidence')}</p><p>No additional experiments or live autonomous feed are available in this release.</p>`;
  if(section==='lineage')html=`<h2>Consumed-parent ancestry</h2><p>These recorded links trace materials consumed during assembly. They do not establish reproduction or inherited function. Select a structure to inspect its material roots and entire interaction history.</p><div class="lineage-list">${Object.entries(w.history).filter(([,o])=>o.parents.length).map(([id,o])=>`<div class="historyitem"><div class="chips">${links(o.parents)} <span>→</span> ${links([id])}</div><p>Assembly event ${o.born_tick} · ${w.objects[id]?'Present':'Retired'}</p></div>`).join('')||'<p>No assemblies recorded at this tick.</p>'}</div>`;
  $('details').innerHTML=html;
  layoutSection();
}
function layoutSection(){
  const universe=section==='universe', inspect=['structures','lineage'].includes(section), playback=['universe','structures','lineage','energy-materials','timeline'].includes(section);
  const observatory=document.querySelector('.observatory'), timeline=document.querySelector('.timeline');
  $('metrics').hidden=!['universe','energy-materials'].includes(section);
  observatory.hidden=!(universe||inspect);
  document.querySelector('.worldpanel').hidden=!universe;
  document.querySelector('.inspector').hidden=!(universe||inspect);
  observatory.classList.toggle('inspector-only',inspect);
  timeline.hidden=!playback;
  $('details').hidden=universe;
  if(universe)$('content').append($('details'));else $('content').insertBefore($('details'),observatory);
  const descriptions={'universe':'Trace the material. Follow the evidence.','experiments':'The published experiment catalog and its recorded scope.','structures':'Select a recorded structure to trace its complete history.','energy-materials':'Conserved model work and material stocks across recorded ticks.','lineage':'Follow consumed materials through recorded assembly links.','timeline':'Inspect the complete event sequence and replay recorded states.','research-evidence':'Source-backed findings, controls, and outstanding questions.','progress':'Seven research stages, with evidence-based status.','system-status':'Recording identity, verification, and the read-only boundary.'};
  $('subtitle').textContent=descriptions[section];
}
function route(){stop();section=location.hash.slice(1)||'universe';if(!sections.some(s=>slug(s)===section))section='universe';document.querySelectorAll('nav a').forEach(a=>{const active=a.hash==='#'+section;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});$('title').textContent=sections.find(s=>slug(s)===section)||'Universe observatory';if(section==='universe')$('title').textContent='Universe observatory';if(recording)renderDetails();window.scrollTo(0,0);}
document.addEventListener('click',e=>{const object=e.target.closest('[data-object]'),tick=e.target.closest('[data-tick]');if(object){selected=object.dataset.object;renderAtlas();renderInspector();$('inspect').hidden=false;$('collapse').setAttribute('aria-expanded','true');if(section!=='universe')document.querySelector('.inspector').scrollIntoView({block:'start'});}if(tick){stop();setTick(Number(tick.dataset.tick));}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('g[data-object]')){e.preventDefault();selected=e.target.dataset.object;renderAtlas();renderInspector();}});
$('navigation').innerHTML=sections.map((s,i)=>`<a href="#${slug(s)}"><span aria-hidden="true">${['◉','▤','⬡','↯','⑂','◷','⌕','↗','⊙'][i]}</span>&nbsp; ${s}</a>`).join('');
window.addEventListener('hashchange',route);route();
$('back').onclick=()=>{stop();setTick(index-1);};$('next').onclick=()=>{stop();setTick(index+1);};$('scrub').oninput=e=>{stop();setTick(Number(e.target.value));};
function play(){if(timer){stop();return;}if(index===states.length-1)setTick(0);$('play').textContent='Pause';timer=setInterval(()=>{if(index>=states.length-1){stop();return;}setTick(index+1);if(index===states.length-1)stop();},Number($('speed').value));}
$('play').onclick=play;$('speed').onchange=()=>{if(timer){stop();play();}};
$('zoomin').onclick=()=>{zoom=Math.min(3,zoom*1.2);renderAtlas();};$('zoomout').onclick=()=>{zoom=Math.max(.5,zoom/1.2);renderAtlas();};$('reset').onclick=()=>{zoom=1;pan={x:0,y:0};renderAtlas();};$('overlay').onchange=renderAtlas;
$('collapse').onclick=()=>{const hidden=!$('inspect').hidden;$('inspect').hidden=hidden;$('collapse').setAttribute('aria-expanded',String(!hidden));};
(async()=>{try{const responses=await Promise.all([fetch('recording.json'),fetch('integrity.json')]);if(responses.some(r=>!r.ok))throw Error('Local recording unavailable');const [raw,integrity]=await Promise.all([responses[0].arrayBuffer(),responses[1].json()]);recording=await Ora.validate(raw,integrity);states=Ora.snapshots(recording);index=states.length-1;$('world').textContent=recording.manifest.identity.world_id+' / seed 1 / bounded reference';$('verification').textContent='✓ Integrity & accounting checked';$('content').hidden=false;$('markers').innerHTML=states.filter(f=>f.event&&['ligated','decayed','captured','reclaimed','copied'].includes(f.event.result.outcome)).map(f=>`<button data-tick="${f.state.simulation_tick}">${f.event.tick} · ${f.event.result.outcome}</button>`).join('');render();}catch(e){$('error').hidden=false;$('error').textContent='No verified recording displayed. '+e.message;$('verification').textContent='Validation failed';}})();
